POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "Livro 02",
    "autor": "Autor 02",
    "npaginas": 450
}

###

GET http://localhost:3333/livro

###

GET http://localhost:3333/livro?search=IFMS

###

PUT  http://localhost:3333/livro/ebc4fc76-c025-4c94-a8ba-19c630871ec7
Content-Type: application/json

{
    "titulo": "Livro: IFMS",
    "autor": "Autor: Anna",
    "npaginas": 100
}

###

DELETE http://localhost:3333/livro/ebc4fc76-c025-4c94-a8ba-19c630871ec7